version: '3.7'
services: 
  database:
    image: "postgres" 
    env_file: 
      - ./database.env
    #volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      #- ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports: 
      - 5432:5432
